-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Asset"
(
    "AssetId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" character varying(500) COLLATE pg_catalog."default",
    "Path" character varying(500) COLLATE pg_catalog."default",
    "Type" character varying(100) COLLATE pg_catalog."default",
    "ParentId" integer,
    CONSTRAINT "PK_Asset" PRIMARY KEY ("AssetId")
);

CREATE TABLE IF NOT EXISTS public."Organization"
(
    "OrganizationId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" character varying(500) COLLATE pg_catalog."default",
    "ParentId" integer,
    "Color" character varying(50) COLLATE pg_catalog."default",
    "IdProfile" integer,
    CONSTRAINT "PK_Organization" PRIMARY KEY ("OrganizationId")
);

CREATE TABLE IF NOT EXISTS public."OrganizationProfile"
(
    "ProfileId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Formation" character varying(500) COLLATE pg_catalog."default",
    "Address" character varying(500) COLLATE pg_catalog."default",
    "Phone" character varying(500) COLLATE pg_catalog."default",
    "Professionals" integer NOT NULL,
    "Employes" integer NOT NULL,
    "Department" character varying(500) COLLATE pg_catalog."default",
    "Province" character varying(500) COLLATE pg_catalog."default",
    "Municipality" character varying(500) COLLATE pg_catalog."default",
    "WaterConnections" integer NOT NULL,
    "ConnectionsWithMeter" integer NOT NULL,
    "ConnectionsWithoutMeter" integer NOT NULL,
    "PublicPools" integer NOT NULL,
    "Latrines" integer NOT NULL,
    "ServiceContinuity" character varying(500) COLLATE pg_catalog."default",
    "OrganizationId" integer NOT NULL,
    CONSTRAINT "PK_OrganizationProfile" PRIMARY KEY ("ProfileId")
);

CREATE TABLE IF NOT EXISTS public."OrganizationToKoboUser"
(
    "KoboUserId" integer NOT NULL,
    "OrganizationId" integer NOT NULL,
    CONSTRAINT "PK_OrganizationToKoboUser" PRIMARY KEY ("KoboUserId", "OrganizationId")
);

CREATE TABLE IF NOT EXISTS public."Role"
(
    "RoleId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT "PK_Role" PRIMARY KEY ("RoleId")
);

CREATE TABLE IF NOT EXISTS public."RoleToAsset"
(
    "RoleId" integer NOT NULL,
    "AssetId" integer NOT NULL,
    CONSTRAINT "PK_RoleToAsset" PRIMARY KEY ("RoleId", "AssetId")
);

CREATE TABLE IF NOT EXISTS public."RoleToKoboUser"
(
    "KoboUserId" integer NOT NULL,
    "RoleId" integer NOT NULL,
    CONSTRAINT "PK_RoleToKoboUser" PRIMARY KEY ("KoboUserId", "RoleId")
);

CREATE TABLE IF NOT EXISTS public."__EFMigrationsHistory"
(
    "MigrationId" character varying(150) COLLATE pg_catalog."default" NOT NULL,
    "ProductVersion" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

ALTER TABLE IF EXISTS public."Organization"
    ADD CONSTRAINT "FK_Organization_OrganizationProfile_IdProfile" FOREIGN KEY ("IdProfile")
    REFERENCES public."OrganizationProfile" ("ProfileId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Organization_IdProfile"
    ON public."Organization"("IdProfile");


ALTER TABLE IF EXISTS public."OrganizationToKoboUser"
    ADD CONSTRAINT "FK_OrganizationToKoboUser_Organization_OrganizationId" FOREIGN KEY ("OrganizationId")
    REFERENCES public."Organization" ("OrganizationId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_OrganizationToKoboUser_OrganizationId"
    ON public."OrganizationToKoboUser"("OrganizationId");


ALTER TABLE IF EXISTS public."RoleToAsset"
    ADD CONSTRAINT "FK_RoleToAsset_Asset_AssetId" FOREIGN KEY ("AssetId")
    REFERENCES public."Asset" ("AssetId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_RoleToAsset_AssetId"
    ON public."RoleToAsset"("AssetId");


ALTER TABLE IF EXISTS public."RoleToAsset"
    ADD CONSTRAINT "FK_RoleToAsset_Role_RoleId" FOREIGN KEY ("RoleId")
    REFERENCES public."Role" ("RoleId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."RoleToKoboUser"
    ADD CONSTRAINT "FK_RoleToKoboUser_Role_RoleId" FOREIGN KEY ("RoleId")
    REFERENCES public."Role" ("RoleId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_RoleToKoboUser_RoleId"
    ON public."RoleToKoboUser"("RoleId");

END;